from ecomsre.evidence.models import (
    CommandLog,
    ControlEvent,
    CycleReport,
    EnvironmentManifest,
    FinalReport,
    FrozenInputs,
    IntegrityManifest,
    MachineManifest,
    PhaseRecord,
    QueryEvidence,
    RunManifest,
    StatisticalEvidence,
)


REQUIRED_FIELDS = {
    RunManifest: {
        "schema_version",
        "run_id",
        "scenario_instance_ref",
        "canonical_state",
        "started_at",
        "ended_at",
        "final_outcome",
        "exit_code",
    },
    MachineManifest: {
        "schema_version",
        "macos_version",
        "macos_build",
        "host_architecture",
        "cpu_model",
        "cpu_count",
        "total_memory_bytes",
        "available_memory_bytes",
        "available_disk_bytes",
        "docker_client_version",
        "docker_server_version",
        "docker_desktop_version",
        "docker_engine",
        "compose_version",
        "docker_cpu_count",
        "docker_memory_bytes",
        "docker_disk_bytes",
    },
    EnvironmentManifest: {
        "schema_version",
        "run_id",
        "owned_resources",
        "ports",
        "startup_state",
        "readiness_state",
        "external_runtime_dependency_observations",
        "disposition",
    },
    FrozenInputs: {
        "schema_version",
        "upstream_tag",
        "upstream_commit",
        "image_lock_sha256",
        "resolved_arm64_digests",
        "compose_config_sha256",
    },
    PhaseRecord: {
        "schema_version",
        "run_id",
        "scenario_phase",
        "cycle_number",
        "utc_started_at",
        "utc_ended_at",
        "monotonic_duration_seconds",
        "probe_fixture_version",
        "query_fixture_version",
        "freshness_start",
        "freshness_end",
    },
    QueryEvidence: {
        "schema_version",
        "run_id",
        "backend",
        "raw_query",
        "raw_response_artifact",
        "started_at",
        "ended_at",
        "status_code",
        "content_sha256",
    },
    StatisticalEvidence: {
        "schema_version",
        "run_id",
        "cycle_number",
        "scenario_phase",
        "getads_attempts",
        "getads_errors",
        "error_rate",
        "wilson_lower",
        "wilson_upper",
        "threshold_passed",
        "sample_timeout",
    },
    CommandLog: {
        "schema_version",
        "run_id",
        "command",
        "arguments",
        "working_directory",
        "started_at",
        "ended_at",
        "monotonic_started_seconds",
        "monotonic_ended_seconds",
        "timeout_seconds",
        "process_exit_code",
        "process_timed_out",
        "classification",
        "terminal_exit_code",
        "reason_code",
        "stdout_artifact",
        "stdout_sha256",
        "stderr_artifact",
        "stderr_sha256",
        "network_access_declared",
        "network_access_scope",
        "filesystem_write_scope",
        "observed_effect_scope",
    },
    FinalReport: {
        "schema_version",
        "run_id",
        "canonical_state",
        "cycle_decisions",
        "telemetry_gate_decisions",
        "overall_outcome",
        "exit_code",
        "failure_reason_codes",
        "environment_disposition",
    },
    IntegrityManifest: {
        "schema_version",
        "run_id",
        "content_hashes",
        "manifest_sha256",
    },
    CycleReport: {
        "cycle_number",
        "passed",
        "reason_codes",
    },
    ControlEvent: {
        "schema_version",
        "run_id",
        "event_id",
        "occurred_at",
        "control_action",
        "feature_flag_key",
        "feature_flag_value",
    },
}


def test_evidence_models_require_every_acceptance_contract_field() -> None:
    for model, expected_fields in REQUIRED_FIELDS.items():
        schema = model.model_json_schema()
        assert set(schema.get("required", ())) == expected_fields
